openapi: 3.0.3
info:
  title: WeAutoTools - 合并 API（资源 + 授权 + 使用限制）
  description: >-
    本规范包含钱包 / 支付 / 商家 管理等资源 API，授权服务器端点（Spring Authorization Server）。
  version: 1.0.0
servers:
  - url: https://api.weautotools.com/v1
  - url: http://localhost:8080/v1
  - url: https://{host}
    variables:
      host:
        default: localhost:8080

tags:
  - name: Wallet
    description: 客户钱包相关操作
  - name: Payment
    description: 充值、支付与退款相关操作
  - name: Merchant
    description: 商家与商品管理
  - name: Admin
    description: 平台管理与运维相关接口
  - name: Auth
    description: 授权服务器端点（OAuth2 / OIDC）
  - name: Usage-Limits
    description: 平台使用次数/频率限制管理

paths:
  /wallet:
    $ref: './paths/wallet/wallet.yaml'
  /wallet/transactions:
    $ref: './paths/wallet/wallet_transactions.yaml'
  /payments/recharge:
    $ref: './paths/payments/payments_recharge.yaml'
  /payments/recharge/callback:
    $ref: './paths/payments/payments_recharge_callback.yaml'
  /orders:
    $ref: './paths/payments/orders.yaml'
  /merchants/apply:
    $ref: './paths/merchants/merchants_apply.yaml'
  /merchants/{merchantId}/products:
    $ref: './paths/merchants/merchants_products.yaml'
  /health:
    $ref: './paths/health.yaml'
  /metrics:
    $ref: './paths/metrics.yaml'
  /admin/audit:
    $ref: './paths/admin/admin_audit.yaml'
  /admin/users:
    $ref: './paths/admin/admin_users.yaml'
  /files/upload:
    $ref: './paths/infra/files_upload.yaml'
  /webhooks/{source}:
    $ref: './paths/infra/webhooks_source.yaml'
  /admin/reconciliation:
    $ref: './paths/admin/admin_reconciliation.yaml'
  /admin/settlements:
    $ref: './paths/admin/admin_settlements.yaml'
  /.well-known/jwks.json:
    $ref: './paths/infra/wellknown_jwks.yaml'
  /.well-known/oauth-authorization-server:
    $ref: './paths/infra/wellknown_oauth_metadata.yaml'
  /api/usage-limits/check:
    $ref: './paths/usage-limits/usage_check.yaml'
  /api/usage-limits/configs/{id}:
    $ref: './paths/usage-limits/usage_configs_id.yaml'

components:
  $ref: './components/components.yaml'